keyword_terms = {
    1: ["Radiology services", "خدمات الأشعة", "'Radiology services' OR 'خدمات الأشعة'"],
    2: ["Imaging center", "مركز الأشعة", "'Imaging center' OR 'مركز الأشعة'"],
    3: [
        "Diagnostic imaging",
        "التصوير التشخيصي",
        "'Diagnostic imaging' OR 'التصوير التشخيصي'",
    ],
    4: ["Medical imaging", "التصوير الطبي", "'Medical imaging' OR 'التصوير الطبي'"],
    5: ["Radiology clinic", "عيادة الأشعة", "'Radiology clinic' OR 'عيادة الأشعة'"],
    6: ["Radiology department", "قسم الأشعة", "'Radiology department' OR 'قسم الأشعة'"],
    7: [
        "Mobile radiology",
        "الأشعة المتنقلة",
        "'Mobile radiology' OR 'الأشعة المتنقلة'",
    ],
    8: [
        "Radiology provider",
        "مقدم خدمات الأشعة",
        "'Radiology provider' OR 'مقدم خدمات الأشعة'",
    ],
    9: ["Hospital", "مستشفى", "'Hospital' OR 'مستشفى'"],
    10: ["Clinic", "عيادة", "'Clinic' OR 'عيادة'"],
    11: ["Imaging center", "مركز تصوير", "'Imaging center' OR 'مركز تصوير'"],
    12: ["Diagnostic center", "مركز تشخيص", "'Diagnostic center' OR 'مركز تشخيص'"],
    13: [
        "Specialty hospital",
        "مستشفى تخصصي",
        "'Specialty hospital' OR 'مستشفى تخصصي'",
    ],
    14: ["Private hospital", "مستشفى خاص", "'Private hospital' OR 'مستشفى خاص'"],
    15: ["Medical complex", "مجمع طبي", "'Medical complex' OR 'مجمع طبي'"],
    16: ["Health center", "مركز صحي", "'Health center' OR 'مركز صحي'"],
    17: ["CT scan", "الأشعة المقطعية", "'CT scan' OR 'الأشعة المقطعية'"],
    18: ["MRI", "التصوير بالرنين المغناطيسي", "'MRI' OR 'التصوير بالرنين المغناطيسي'"],
    19: [
        "PET-CT",
        "التصوير المقطعي بالإصدار البوزيتروني",
        "'PET-CT' OR 'التصوير المقطعي بالإصدار البوزيتروني'",
    ],
    20: ["X-ray", "الأشعة السينية", "'X-ray' OR 'الأشعة السينية'"],
    21: ["Ultrasound", "الموجات فوق الصوتية", "'Ultrasound' OR 'الموجات فوق الصوتية'"],
    22: ["Mammogram", "تصوير الثدي الشعاعي", "'Mammogram' OR 'تصوير الثدي الشعاعي'"],
    23: ["DEXA scan", "فحص كثافة العظام", "'DEXA scan' OR 'فحص كثافة العظام'"],
    24: ["Fluoroscopy", "التنظير التألقي", "'Fluoroscopy' OR 'التنظير التألقي'"],
    25: [
        "Interventional radiology",
        "الأشعة التداخلية",
        "'Interventional radiology' OR 'الأشعة التداخلية'",
    ],
}
